spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:casadb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

# H2 Console
spring.h2.console.enabled: ${H2_CONSOLE_ENABLED:true}
spring.h2.console.path: ${H2_CONSOLE_PATH:/h2-console}

# Porta opcional (mude se precisar)
server:
  port: ${SERVER_PORT:8080}
